Show "App Usage" in Bar chart using Room Database (#8)
* Added 'Search' Feature in App List Screen

* Close the keyboard when user press on "search" button of keyboard

* Added FirebaseAnalytics without ads

* WIP - Get App Usage time for 24 hr

- Opened "AppDetailsActivity" when user click on appItem from the App list
- Pass model class to "AppDetailsActivity"

* Completed - Stored App Usage time in SharedPref

- Store appStart time in Preference when user click on 'Continue' button
- When user change the app when calculate the difference and store the total app usage time in Preference for that specific package name

* Changed some key names in constants and removed unused keys

* Fixed same package add multiple times in favAppList and some improvements

Fix:
- called 'rawSwitch.setOnCheckedChangeListener(null);' before 'rawSwitch.setChecked(appInfoModel.isFavorite())'.
Issue was when user do search then, 'notifyDataSetChanged()' was called and then 'rawSwitch.setChecked()' called. As the 'setChecked()' called the 'setOnCheckedChangeListener()' was called and the appItems were added and removed.

Improvements:
- Added 'isFavorite' parameter in 'AppInfoModel'
- Set the 'isFavorite' true for the apps which are added in favAppList. Did that in 'PermissionHelper' when load installed apps

* Made Common function to get favAppList from Preference

* Added App open time with other app info in Room Database

* completed - Calculate Total App Usage Time using Room Database

* Fixed - Sometimes 'closedTime' and 'appUsageTime' was not update

- Update using 'AppUsage' Entity
- Store appUsageStartTime time instead of currentTime

* Fixed - TotalAppUsage was not proper

- For 'TotalAppUsage', did the some of all AppUsage times. Instead of it applied the some of only the specific app.

* Show 'TotalAppUsageTime' for User selected date

* Hide "Previous" button when the data is not available for that date and "Next" button when the next the date is Current Date

* Show app Usage time with two units like "1min 5secs"

* Show "0 sec" when no usage

* - Instead of 'GONE' used 'INVISIBLE'
- Get appUsage's First date from DB based on app's package name instead of first id
- Open 'Detail' screen for the favApps (selected apps)

* - Open DatePicker on click of Date (tvDate)
- Show appUsage for the selected date of DatePicker
- Optimize some code

* - Disable Date in the DatePicker for which appUsage not available

* Check the appUsage Data available or not for specific package before open the detail page

* WIP - Show App Usage Weekly (MON - SUN)

* completed - Show App Usage Weekly (MON - SUN)

* - Optimise some code
- Get Start and End date when user select date for DatePicker

* Solved app crash issue

Issue: Sometime app was crashed when load apps and get bitmap for the installed apps

Error: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sevensec/com.sevensec.activities.MainActivity}: java.lang.IllegalArgumentException: width and height must be > 0

* Show BarChart of AppUsage for weekly Data

* Show y-axis label in "seconds" OR "minutes" OR "hour" based on the maximum value of the week

* Made the text of "AppUsageTime" short to show it on the bar

* Remove the "0 s" from the graph where the app Usage data not available

* Remove "days" calculation from "getAppUsageTimeInFormat()"

- It will not needed as we are showing the app usage data for each day

* - Show "1h 3m", "1m 0s" format for y axis
- On the bar show only "1h 3m", "1m 6s". Not like "1h 0m".

* Show app Usage For Current Date in Details screen

* - Added Back Button in Detail screen
- Put title ""<appName> Usage"
- Remove app name from detail screen as we are showing it in title

* Show Days from "Sun" instead of "Mon"

* Added numberOfDays in Constants file

* Removed restriction for previous week

- Removed restriction from DatePicker and Previous button to check the previous week's usage data when the data is not available
- Show "No Data" view when the usage data not available

* Changed color of the Bar in chart

* Show message when user click on the disabled app to check app usage

* Added animation in Bar

* Did the "Login" from the "splash" screen instead of "onBoarding" screen

* - Show only Retry button instead of illustration in the splash screen
- Show snackBar when internet not available
- If login done then, not check for internet. Directly check that user already visit onboarding or not
- on loginSuccess open the onBoarding screen instead of check that user already visit it or not

* Took "App Close Time" from Room DB instead of Shared Preference

* Removed the Commented code for calculate "AppSwitchDuration" and "AppUsage" using preference

* Changed DatePicker dialog color

* Changed version to 4 (1.0.2)